config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/show'

  get 'comments/new'

  get 'comments/create'

  get 'comments/update'

  get 'comments/destroy'

  root to: 'welcome#index'
  get 'welcome/index'
  resources :articles do
	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: {minimum:5}, uniqueness: true
	has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :fetch_article, only: [:show,:edit,:update,:destroy]
	http_basic_authenticate_with name: 'prateek', password: 'reportgarden', except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article = Article.create(article_params);
		if @article.errors.any?
			render 'new'
		else
			redirect_to @article
		end
	end

	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end
	

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end

	def fetch_article
		@article = Article.find(params[:id])
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: 'prateek', password: 'reportgarden1', only: :destroy
 
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @article.comments.find(params[:id]).destroy
    redirect_to article_path @article
  end

  private
  def comment_params
    params.require(:comment).permit(:commentor,:comment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<% if @article.errors.any?%>
<div id="error_description">
	<%=pluralize(@article.errors.size, 'error')%> prevented the article from being saved
	<ul>
	<% @article.errors.full_messages.each do |m| %>
		<li><%= m %></li>
	<%end%> 
	</ul>
</div>
<%end%>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path%>

app/views/articles/index.html.erb
<h1> All Articles </h1>
<%= link_to 'Create New', new_article_path %>
<table>
	<th>
		<td>Title</td>
		<td>Text</td>
	</th>
	<% @articles.each do |a| %>
	<tr>
		<td><%= a.title %></td>
		<td><%= a.text %></td>
		<td><%= link_to 'Show', article_path(a) %></td>
		<td><%= link_to 'Edit', edit_article_path(a) %></td>
		<td><%= link_to 'Delete', article_path(a), method: :delete, data:{confirm: 'Are you sure'} %></td>
	</tr>
	<% end %>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%= render 'form' %>
<%= link_to 'Back', articles_path%>

app/views/articles/show.html.erb
<h1>View Article</h1>
<%= link_to 'All Articles', articles_path %>
<%= link_to 'Edit Article', edit_article_path %>
<%= link_to 'Delete', article_path, method: :delete, data: { confirm: 'Are you sure' } %>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<% if @article.comments.size>0%>
<h2> All Comments</h2>
<%= render @article.comments%>
<%end%>

<h2>Add Comment</h2>
<%= render 'comments/form'%>


	

app/views/comments/_comment.html.erb
<div>
    <strong>Commentor : </strong> <p><%= comment.commentor %></p> 
    <strong>Comment : </strong> <p><%= comment.comment %></p> 
    <%= link_to "Delete Comment", article_comment_path(comment.article, comment), method: :delete, data: {confirm: 'Are you sure'} %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.new]) do |f| %>
  <p>
    <%= f.label :commentor %><br>
    <%= f.text_field :commentor %>
  </p>
 
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blogs', controller: 'articles' %>